/* नन्हा स्कूल — content for "बड़े होकर" (dream jobs). Pure data, no logic.
   Every job shows two characters (mixed genders and skin tones) so any child can see themselves.
   does: what they do (2 short sentences); act: a pretend-play moment; link: the covert tie to
   today's habits. habit: the real-life habit the link points at (or null). */
(function () {
  "use strict";
  var NS = window.NS || (window.NS = {});
  NS.content = NS.content || {};

  NS.content.careers = [
    { id: "doctor", icon: "🩺", people: ["👩‍⚕️", "👨🏽‍⚕️"], color: "#EF5350", habit: "read",
      title: { hi: "डॉक्टर", en: "Doctor" },
      does: { hi: "डॉक्टर बीमार लोगों को ठीक करते हैं। वे दिल की धड़कन सुनते हैं और दवाई देते हैं।", en: "Doctors help sick people get well. They listen to heartbeats and give medicine." },
      act: { emoji: "❤️", hi: "डॉक्टर की तरह अपने दिल की धड़कन सुनो — हाथ सीने पर रखो। धक-धक, धक-धक!", en: "Like a doctor, feel your heartbeat — put your hand on your chest. Thump-thump, thump-thump!" },
      link: { hi: "डॉक्टर रोज़ थोड़ा-थोड़ा पढ़ते हैं। तुम भी रोज़ कुछ नया सीखो!", en: "Doctors read a little every day. You can learn something new every day too!" } },
    { id: "farmer", icon: "🌾", people: ["👩🏾‍🌾", "👨‍🌾"], color: "#7CB342", habit: "sleep",
      title: { hi: "किसान", en: "Farmer" },
      does: { hi: "किसान खेत में बीज बोते हैं। हम जो अनाज और सब्ज़ियाँ खाते हैं, वे किसान ही उगाते हैं।", en: "Farmers plant seeds in the fields. They grow the grain and vegetables we eat." },
      act: { emoji: "🌱", hi: "किसान की तरह बीज बोओ — झुको, मिट्टी खोदो, बीज डालो और पानी दो!", en: "Plant seeds like a farmer — bend down, dig, drop the seed and water it!" },
      link: { hi: "किसान रात को जल्दी सोते हैं और सूरज के साथ सुबह जल्दी उठते हैं।", en: "Farmers sleep early and wake up early with the sun." } },
    { id: "teacher", icon: "📚", people: ["👩🏻‍🏫", "👨🏾‍🏫"], color: "#FFA000", habit: "read",
      title: { hi: "शिक्षक", en: "Teacher" },
      does: { hi: "शिक्षक बच्चों को पढ़ना, लिखना और गिनना सिखाते हैं। वे बहुत प्यार से समझाते हैं।", en: "Teachers help children read, write and count. They explain things kindly." },
      act: { emoji: "🔢", hi: "टीचर बनो! अपने खिलौनों को गिनती सिखाओ — एक, दो, तीन, चार, पाँच!", en: "Be a teacher! Teach your toys to count — one, two, three, four, five!" },
      link: { hi: "टीचर रोज़ समय पर स्कूल पहुँचते हैं, ताकि कोई बच्चा इंतज़ार न करे।", en: "Teachers reach school on time every day, so no child has to wait." } },
    { id: "scientist", icon: "🔬", people: ["👩🏾‍🔬", "👨🏻‍🔬"], color: "#00897B", habit: null,
      title: { hi: "वैज्ञानिक", en: "Scientist" },
      does: { hi: "वैज्ञानिक सवाल पूछते हैं — ऐसा क्यों होता है? फिर वे ध्यान से देखकर जवाब ढूँढ़ते हैं।", en: "Scientists ask questions — why does this happen? Then they look carefully to find the answer." },
      act: { emoji: "🔍", hi: "पास की कोई चीज़ ध्यान से देखो। उसका रंग क्या है? वह भारी है या हल्की?", en: "Look carefully at something near you. What colour is it? Is it heavy or light?" },
      link: { hi: "वैज्ञानिक एक समय पर एक काम, पूरे ध्यान से करते हैं।", en: "Scientists do one thing at a time, with full attention." } },
    { id: "astronaut", icon: "🚀", people: ["👩‍🚀", "👨🏽‍🚀"], color: "#3949AB", habit: "eat",
      title: { hi: "अंतरिक्ष यात्री", en: "Astronaut" },
      does: { hi: "अंतरिक्ष यात्री रॉकेट में बैठकर तारों की ओर जाते हैं। वहाँ वे हवा में तैरते हैं!", en: "Astronauts ride rockets up towards the stars. Up there, they float in the air!" },
      act: { emoji: "🚀", hi: "रॉकेट बनो! नीचे बैठो, गिनो — पाँच, चार, तीन, दो, एक — और ऊपर कूदो!", en: "Be a rocket! Crouch down, count — five, four, three, two, one — and jump up high!" },
      link: { hi: "अंतरिक्ष यात्री अच्छा खाना खाते हैं और रोज़ कसरत करते हैं।", en: "Astronauts eat healthy food and exercise every day." } },
    { id: "pilot", icon: "✈️", people: ["👩🏻‍✈️", "👨🏾‍✈️"], color: "#039BE5", habit: null,
      title: { hi: "पायलट", en: "Pilot" },
      does: { hi: "पायलट हवाई जहाज़ उड़ाते हैं। वे लोगों को दूर-दूर के शहरों तक ले जाते हैं।", en: "Pilots fly aeroplanes. They take people to faraway cities." },
      act: { emoji: "✈️", hi: "दोनों हाथ फैलाओ और हवाई जहाज़ की तरह उड़ो — ज़ूँऊँऊँ!", en: "Spread your arms and fly like an aeroplane — zoooom!" },
      link: { hi: "पायलट हर काम समय पर करते हैं — इसीलिए जहाज़ समय पर उड़ता है।", en: "Pilots do everything on time — that's why the plane leaves on time." } },
    { id: "engineer", icon: "🔧", people: ["👩🏽‍🔧", "👨‍🔧"], color: "#6D4C41", habit: null,
      title: { hi: "इंजीनियर", en: "Engineer" },
      does: { hi: "इंजीनियर पुल, सड़कें, मशीनें और घर बनाते हैं। वे पहले सोचते हैं, फिर बनाते हैं।", en: "Engineers build bridges, roads, machines and houses. They think first, then build." },
      act: { emoji: "🧱", hi: "हाथों से ऊँची मीनार बनाओ — एक मुट्ठी के ऊपर दूसरी मुट्ठी, ऊपर, और ऊपर!", en: "Build a tall tower with your hands — one fist on top of the other, up and up!" },
      link: { hi: "इंजीनियर ध्यान से नापते हैं और काम पूरा करके ही उठते हैं।", en: "Engineers measure carefully and finish what they start." } },
    { id: "artist", icon: "🎨", people: ["👩🏾‍🎨", "👨🏻‍🎨"], color: "#D81B60", habit: null,
      title: { hi: "कलाकार", en: "Artist" },
      does: { hi: "कलाकार रंगों से सुंदर चित्र बनाते हैं। वे दुनिया को रंगीन बनाते हैं।", en: "Artists make beautiful pictures with colours. They make the world colourful." },
      act: { emoji: "☀️", hi: "अपनी उँगली से हवा में एक बड़ा, गोल सूरज बनाओ!", en: "Draw a big round sun in the air with your finger!" },
      link: { hi: "कलाकार रोज़ थोड़ा अभ्यास करते हैं, तभी चित्र इतने सुंदर बनते हैं।", en: "Artists practise a little every day — that's how pictures get so beautiful." } },
    { id: "athlete", icon: "🏅", people: ["🏃🏽‍♀️", "⛹🏻‍♂️"], color: "#F4511E", habit: "sleep",
      title: { hi: "खिलाड़ी", en: "Athlete" },
      does: { hi: "खिलाड़ी दौड़ते हैं, कूदते हैं और खेलते हैं। वे अपनी टीम के साथ मिलकर खेलते हैं।", en: "Athletes run, jump and play. They play together with their team." },
      act: { emoji: "🏃", hi: "अपनी जगह पर दौड़ो — टप-टप-टप! अब तीन बार ऊँचा कूदो!", en: "Run on the spot — tap-tap-tap! Now jump up high three times!" },
      link: { hi: "खिलाड़ी रात को समय पर सोते हैं, ताकि सुबह ताक़त से भरे रहें।", en: "Athletes go to sleep on time, so they're full of energy in the morning." } },
    { id: "police", icon: "🚓", people: ["👮🏽‍♀️", "👮🏻‍♂️"], color: "#1E88E5", habit: null,
      title: { hi: "पुलिस", en: "Police officer" },
      does: { hi: "पुलिस वाले हम सबकी रक्षा करते हैं। वे सड़क पर सबको सुरक्षित रखते हैं।", en: "Police officers keep us all safe. They help everyone on the road stay safe." },
      act: { emoji: "✋", hi: "सीधे खड़े हो जाओ, हाथ उठाओ और बोलो — “रुको!” अब हाथ हिलाकर — “चलो!”", en: "Stand up straight, raise your hand and say “Stop!” Now wave — “Go!”" },
      link: { hi: "पुलिस वाले नियम मानते हैं और समय पर ड्यूटी पर पहुँचते हैं।", en: "Police officers follow the rules and reach work on time." } },
    { id: "nurse", icon: "💉", people: ["👨🏻‍⚕️", "👩🏾‍⚕️"], color: "#EC407A", habit: null,
      title: { hi: "नर्स", en: "Nurse" },
      does: { hi: "नर्स मरीज़ों का ध्यान रखते हैं। वे दवाई देते हैं और प्यार से बात करते हैं।", en: "Nurses take care of patients. They give medicine and talk kindly." },
      act: { emoji: "🧼", hi: "नर्स की तरह हाथ धोने का खेल करो — हथेली, उँगलियाँ, अँगूठा, सब गोल-गोल!", en: "Pretend to wash your hands like a nurse — palms, fingers, thumbs, all round and round!" },
      link: { hi: "नर्स बार-बार हाथ धोते हैं, ताकि कीटाणु भाग जाएँ।", en: "Nurses wash their hands often, so germs run away." } },
    { id: "chef", icon: "🍳", people: ["👨🏽‍🍳", "👩🏻‍🍳"], color: "#FB8C00", habit: "eat",
      title: { hi: "शेफ़", en: "Chef" },
      does: { hi: "शेफ़ स्वादिष्ट खाना बनाते हैं। वे दाल, सब्ज़ी और फल से सेहतमंद खाना पकाते हैं।", en: "Chefs cook tasty food. They make healthy meals with dal, vegetables and fruit." },
      act: { emoji: "🥄", hi: "बड़ा चम्मच पकड़ो और कड़ाही में गोल-गोल चलाओ — छन-छन!", en: "Hold a big spoon and stir the pot round and round — sizzle-sizzle!" },
      link: { hi: "शेफ़ जानते हैं — समय पर खाना खाने से ताक़त आती है।", en: "Chefs know — eating on time gives us energy." } },
    { id: "soldier", icon: "🪖", people: ["👩🏽", "👨🏾"], color: "#558B2F", habit: "help",
      title: { hi: "सैनिक", en: "Soldier" },
      does: { hi: "सैनिक हमारे देश की रक्षा करते हैं। वे बहादुर होते हैं और एक-दूसरे का साथ देते हैं।", en: "Soldiers protect our country. They are brave and look after each other." },
      act: { emoji: "🥾", hi: "सीधे खड़े हो जाओ और कदमताल करो — लेफ़्ट, राइट, लेफ़्ट, राइट!", en: "Stand tall and march — left, right, left, right!" },
      link: { hi: "सैनिक सुबह जल्दी उठते हैं और अपना बिस्तर ख़ुद ठीक करते हैं।", en: "Soldiers wake up early and make their own beds." } },
    { id: "musician", icon: "🥁", people: ["👩🏻", "👨🏾"], color: "#8E24AA", habit: null,
      title: { hi: "संगीतकार", en: "Musician" },
      does: { hi: "संगीतकार गाना गाते हैं। वे ढोलक, बाँसुरी और सितार बजाते हैं।", en: "Musicians sing songs. They play the drum, the flute and the sitar." },
      act: { emoji: "👏", hi: "ताली से ताल बजाओ — ताली, ताली, रुको… ताली, ताली, रुको!", en: "Clap a beat — clap, clap, stop… clap, clap, stop!" },
      link: { hi: "संगीतकार रोज़ थोड़ा अभ्यास करते हैं, थोड़ा-थोड़ा करके सीखते हैं।", en: "Musicians practise a little every day, learning bit by bit." } },
    { id: "tailor", icon: "🧵", people: ["👩🏽", "👨🏻‍🦳"], color: "#9E9D24", habit: null,
      title: { hi: "दर्जी", en: "Tailor" },
      does: { hi: "दर्जी कपड़ा नापते हैं, काटते हैं और सिलते हैं। हमारे सुंदर कपड़े वही बनाते हैं।", en: "Tailors measure, cut and sew cloth. They make our lovely clothes." },
      act: { emoji: "🪡", hi: "सुई में धागा डालने का नाटक करो — आँखें ध्यान से, हाथ धीरे से!", en: "Pretend to thread a needle — careful eyes, gentle hands!" },
      link: { hi: "दर्जी बहुत ध्यान से काम करते हैं — एक-एक टाँका।", en: "Tailors work very carefully — one stitch at a time." } },
    { id: "driver", icon: "🚌", people: ["👩🏾", "👨🏽"], color: "#F9A825", habit: null,
      title: { hi: "ड्राइवर", en: "Driver" },
      does: { hi: "ड्राइवर बस, ट्रक और गाड़ी चलाते हैं। वे हमें सुरक्षित घर और स्कूल पहुँचाते हैं।", en: "Drivers drive buses, trucks and cars. They take us safely home and to school." },
      act: { emoji: "🚦", hi: "स्टीयरिंग पकड़ो और गाड़ी चलाओ — लाल बत्ती पर रुको, हरी पर चलो! पों-पों!", en: "Hold the steering wheel and drive — stop at red, go at green! Beep-beep!" },
      link: { hi: "ड्राइवर समय पर निकलते हैं, ताकि सब समय पर पहुँचें।", en: "Drivers leave on time, so everyone gets there on time." } }
  ];
})();
