// Writes web/js/content/images.js (emoji → realistic picture) and web/img/real/CREDITS.txt from
//   tools/images/fluent.json   Fluent Emoji 3D renders (fetched by fetch-fluent.py)
//   tools/images/photos.json   optional real photographs, human-picked and human-approved
//                              (written by fetch-photos.mjs --publish); a photo wins over the
//                              Fluent picture for the same emoji.
// Run: node tools/images/build-images.mjs        (no dependencies; checks every file exists)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const WEB = path.join(ROOT, "web");
const FLUENT = path.join(ROOT, "tools/images/fluent.json");
const PHOTOS = path.join(ROOT, "tools/images/photos.json");
const OUT_JS = path.join(WEB, "js/content/images.js");
const CREDITS = path.join(WEB, "img/real/CREDITS.txt");

export const normKey = (k) => String(k).replace(/[︎️]/g, "").trim();

const MIT = `MIT License

Copyright (c) Microsoft Corporation.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE`;

function main() {
  const fluent = JSON.parse(fs.readFileSync(FLUENT, "utf8"));
  const photos = fs.existsSync(PHOTOS) ? JSON.parse(fs.readFileSync(PHOTOS, "utf8")) : [];
  const map = new Map();
  const problems = [];
  const slugRe = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

  for (const it of fluent) {
    if (!slugRe.test(it.slug)) problems.push("bad slug " + it.slug);
    const url = "img/real/" + it.slug + ".webp";
    if (!fs.existsSync(path.join(WEB, url))) problems.push("missing " + url + " (run tools/images/fetch-fluent.py)");
    for (const k of it.keys) map.set(normKey(k), url);
  }
  for (const p of photos) {
    if (!p.approvedBy) { problems.push("photo " + p.slug + " has no approvedBy — not published"); continue; }
    if (!/^img\/real\/photo\/[a-z0-9-]+\.(webp|jpg|png)$/.test(p.file)) problems.push("bad photo path " + p.file);
    if (!fs.existsSync(path.join(WEB, p.file))) problems.push("missing " + p.file);
    for (const k of p.keys) map.set(normKey(k), p.file);
  }
  if (problems.length) { console.error(problems.join("\n")); process.exit(1); }

  const keys = [...map.keys()].sort((a, b) => map.get(a).localeCompare(map.get(b)) || a.localeCompare(b));
  const lines = keys.map((k) => "    " + JSON.stringify(k) + ": " + JSON.stringify(map.get(k)));
  const js = `/* नन्हा स्कूल — realistic pictures for the emoji that the lessons, games and stories use as pictures.
   GENERATED by tools/images/build-images.mjs from tools/images/fluent.json (+ photos.json) —
   edit those and re-run; see docs/IMAGES.md. Pictures: web/img/real/ (credits in CREDITS.txt).

   NS.images          { "<emoji, without U+FE0F>": "img/real/<slug>.webp", … }  (paths relative to index.html)
   NS.img(key)        the picture for one emoji, or null. U+FE0E/U+FE0F are ignored; skin tones are kept
                      when that picture exists, otherwise the same person in another tone is used.
   NS.img.parts(text) [{key, url}] for each emoji in a string ("🍎🍎🍎", "🐦🌳☀️"); url is null when there
                      is no picture (show the emoji then). Other characters are skipped.
   Pure data + two tiny helpers: no DOM, no network at load time. */
(function () {
  "use strict";
  var NS = window.NS || (window.NS = {});
  NS.content = NS.content || {};

  var IMAGES = {
${lines.join(",\n")}
  };

  var VS = /[\\uFE0E\\uFE0F]/g;
  var TONE = /\\uD83C[\\uDFFB-\\uDFFF]/g;
  var has = function (o, k) { return Object.prototype.hasOwnProperty.call(o, k); };
  var LOOSE = {};   // the same keys without skin tones (first picture wins)
  Object.keys(IMAGES).forEach(function (k) { var p = k.replace(TONE, ""); if (!has(LOOSE, p)) LOOSE[p] = IMAGES[k]; });
  function img(key) {
    if (typeof key !== "string" || !key) return null;
    var k = key.replace(VS, "").trim();
    if (has(IMAGES, k)) return IMAGES[k];
    var plain = k.replace(TONE, "");
    if (has(IMAGES, plain)) return IMAGES[plain];
    return has(LOOSE, plain) ? LOOSE[plain] : null;
  }
  var SEQ = null;
  try {
    SEQ = new RegExp("\\\\p{Regional_Indicator}{2}|[#*0-9]\\\\uFE0F?\\\\u20E3|\\\\p{Extended_Pictographic}[\\\\uFE0E\\\\uFE0F]?\\\\p{Emoji_Modifier}?" +
      "(?:\\\\u200D\\\\p{Extended_Pictographic}[\\\\uFE0E\\\\uFE0F]?\\\\p{Emoji_Modifier}?)*", "gu");
  } catch (e) { SEQ = null; }   // very old engines: fall back to one emoji per code point
  img.parts = function (text) {
    var out = [];
    if (typeof text !== "string" || !text) return out;
    var found = SEQ ? (text.match(SEQ) || []) : Array.from(text).filter(function (ch) { return ch.codePointAt(0) > 0x2000 && !/[\\uFE0E\\uFE0F\\u200D]/.test(ch); });
    for (var i = 0; i < found.length; i++) out.push({ key: found[i], url: img(found[i]) });
    return out;
  };

  NS.images = IMAGES;
  NS.img = img;
})();
`;
  fs.writeFileSync(OUT_JS, js);

  const flist = fluent.map((it) => "  " + (it.slug + ".webp").padEnd(42) + " " + it.keys.join(" ") + "  " +
    (it.compose ? "composed from: " + it.compose.map((c) => c.src).join(" + ") : it.src)).join("\n");
  const plist = photos.filter((p) => p.approvedBy).map((p) =>
    `  ${p.file}  ${p.keys.join(" ")}\n    "${p.title}" by ${p.author}, ${p.license}${p.licenseUrl ? " (" + p.licenseUrl + ")" : ""}\n    source: ${p.source}${p.modified ? "\n    changes: " + p.modified : ""}\n    approved for children by: ${p.approvedBy}`).join("\n");
  const credits = `Pictures in web/img/real/ — credits and licences
=================================================

1. Fluent Emoji 3D renders (all *.webp files directly in this folder)

   Fluent Emoji © Microsoft Corporation, MIT License.
   Source: https://github.com/microsoft/fluentui-emoji (assets/<name>/3D/*.png, branch main)
   Changes: converted from PNG to WebP at the original 256x256. The three family-*.webp
   pictures are composed from several Fluent person renders (Fluent has no 3D family emoji).
   People and hands use the Fluent "Medium" skin-tone render unless a specific tone is asked for.

${MIT}

   Files (picture, emoji it stands for, Fluent source):
${flist}
${plist ? `
2. Photographs (web/img/real/photo/), each chosen and approved by a person

${plist}
` : `
2. Photographs: none yet. See docs/IMAGES.md for how real photographs can be added later.
`}`;
  fs.writeFileSync(CREDITS, credits);
  console.log("images.js:", keys.length, "keys →", new Set(map.values()).size, "pictures; CREDITS.txt written");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) main();
